// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.database;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240306161743_BaseMigration")]
    partial class BaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HomePhone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SiteId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellPhone = "0123456789",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9885),
                            Email = "john@doe.com",
                            Firstname = "John",
                            HomePhone = "0123456789",
                            Lastname = "Doe",
                            ServiceId = 1,
                            SiteId = 1,
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9886)
                        },
                        new
                        {
                            Id = 2,
                            CellPhone = "9876543210",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9888),
                            Email = "jane@smith.com",
                            Firstname = "Jane",
                            HomePhone = "9876543210",
                            Lastname = "Smith",
                            ServiceId = 2,
                            SiteId = 2,
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9889)
                        },
                        new
                        {
                            Id = 3,
                            CellPhone = "1234567890",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9891),
                            Email = "michael@johnson.com",
                            Firstname = "Michael",
                            HomePhone = "1234567890",
                            Lastname = "Johnson",
                            ServiceId = 3,
                            SiteId = 3,
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9892)
                        });
                });

            modelBuilder.Entity("api.Model.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9717),
                            Name = "Development",
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9754)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9758),
                            Name = "Marketing",
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9759)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9761),
                            Name = "Commercial",
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9762)
                        });
                });

            modelBuilder.Entity("api.Model.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Paris",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9854),
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9855)
                        },
                        new
                        {
                            Id = 2,
                            City = "Nantes",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9857),
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9858)
                        },
                        new
                        {
                            Id = 3,
                            City = "Toulouse",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9859),
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9860)
                        },
                        new
                        {
                            Id = 4,
                            City = "Nice",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9861),
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9862)
                        },
                        new
                        {
                            Id = 5,
                            City = "Lile",
                            CreatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9863),
                            UpdatedAt = new DateTime(2024, 3, 6, 17, 17, 43, 164, DateTimeKind.Local).AddTicks(9864)
                        });
                });

            modelBuilder.Entity("api.Model.Employee", b =>
                {
                    b.HasOne("api.Model.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Model.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
